from bot.handlers.start_handler import *
from bot.handlers.send_admin import *
from bot.handlers.referal import *
from bot.handlers.cabinet import *
from bot.handlers.eggs import *
from bot.handlers.exchange import *
from bot.handlers.info import *
from bot.handlers.credits import *
from bot.handlers.purchase import *
from bot.handlers.farm import *
from bot.handlers.admin import *
from bot.handlers.advert import *
from bot.handlers.add_sub_money import *
from bot.handlers.settings import *
from bot.handlers.user_setting import *
